-- SUPERSEDED — no-op. Kept for history.
--
-- This legacy script (a) created product tables without the unique constraints the
-- rate updater upserts onto, and (b) contains invalid SQL on the bonds table:
--   UNIQUE (bond_name, bond_type, COALESCE(tenor, ''))
-- Postgres does not allow expressions in a table-level UNIQUE constraint, so this
-- file errors with "syntax error at or near (".
--
-- It is fully replaced by:
--   0001_init.sql                — canonical schema for all tables
--   0002_fix_product_tables.sql  — rebuilds credit_cards / home_loans with constraints
--
-- Left as a harmless no-op so `npm run db:init` (which runs every *.sql here) passes.
select 1;
